Adds getIsRecording method.
negativetwelve/react-native-lookback pull request #23
Opened 2017-03-15 15:42 UTC by jasonmerino

Needed to get current recording status of Lookback.io SDK.

2017-03-15 23:12 UTC, negativetwelve requested changes
thanks for the PR @jasonmerino! Just a small formatting issue then we can merge this in. Does this require an SDK version bump?

2017-03-15 23:12 UTC, negativetwelve commented on ios/RNLookback.m
> +    resolve([NSNumber numberWithBool:[[Lookback sharedLookback] isRecording]]);
can you match the rest of the file's indentation? we use two spaces everywhere, thanks!

2017-03-15 23:12 UTC, negativetwelve commented on readme.md
> -Lookbac.exitedView('my-view');
good catch!

2017-03-16 00:00 UTC, jasonmerino commented
Okay, I believe I've fixed up the formatting to match.

I don't think there needs to be any bump of the Lookback SDK. Our podfile says we've got `"LookbackSafe", "~> 1.4.1"` installed. I'm not sure if the `isRecording` getter is a new method to the Lookback SDK though.

As far as NPM goes, it's additive and I didn't change any of the existing methods, so it should be good to go out as a minor release there.

2017-03-17 22:39 UTC, merged

2017-03-17 22:41 UTC, negativetwelve commented
looks good! Release on npm as `1.3.1`